exports.react = require('react')
exports['reactDom'] = require('react-dom')
exports['propTypes'] = require('prop-types')
exports.classnames = require('classnames')
exports.proppy = require('proppy')
exports['proppyReact'] = require('proppy-react')
// exports.antd = require('antd')
// exports['antdcss'] = require('antd/dist/antd.css')